### ISSUE TITLE
it possible to support different languages or we should fork it? 

### ISSUE THREAD

**Issue by gilgamezh** [rougeth/i17obot#5]
We want to use it for the spanish translation

**Comment by rougeth** [comment]
Hey @gilgamezh! Awesome to see interest in the project from you folks! I've always saw the i17obot as a tool that would be helpful for other languages. Currently its code focus only on pt_br, but I'd be thrilled to work on making it generally available.

Were you able to understand its main features? If so, is there anything other feature that you believe it'd be helpful for Spanish community?

**Comment by gilgamezh** [comment]
I think the bot is just awesome. Loved the tutorial. 

With the current features I would like to add support for spanish translation (We can help there) and that should be our starting point

**Comment by rougeth** [comment]
I have news! :) Just deployed a new version of [@i17obot](https://t.me/i17obot) with the following changes:

- `/language` command allow us to choose which language we want to translate the documentation. For now, only Brazilian Portuguese or Spanish as options.
- The `/translate` command will return the text to be translated and its url according to what the user configured as its language.

I believe these changes will unblock you from using the bot for Spanish translation. Let me know if you have any problem using it.

Next steps would be to translate what the bot says. This one might take longer, so any help is appreciated.

**Comment by marcorichetta** [comment]
@rougeth Good to hear that!

> Next steps would be to translate what the bot says.

If you refer to the content on `messages.py`, maybe we can create a spanish version of it.

**Comment by rougeth** [comment]
@marcorichetta yes, I believe a Spanish version of `messages.py` will be the easiest/fastest way.

**Comment by rougeth** [comment]
@gilgamezh @marcorichetta Just added [i17obot/templates/es.py](https://github.com/rougeth/i17obot/blob/master/i17obot/templates/es.py), now it's with you :D

**Comment by marcorichetta** [comment]
@rougeth I was just about to write you because I saw you made the new branch (i18n).

Should we add the spanish version of the commands? Here for example: https://github.com/rougeth/i17obot/blob/19cc65f5583c66b79265fc076ac994d72f150491/i17obot/main.py#L43

**Comment by rougeth** [comment]
Yep, go ahead.

**Comment by marcorichetta** [comment]
@rougeth Made a PR (#9) with the initial translation.

**Comment by rougeth** [comment]
@marcorichetta merged and deployed :) ﻿Muchas gracias!

**Comment by marcorichetta** [comment]
I started the bot with `/start` but it didn't answer anything, despite it appears as it were writing.
I was able to set it to Spanish with `/language`.
Then I tried the other commands and they worked except `/ayuda`.

**Comment by rougeth** [comment]
There were two issues, a missing `_` and the Wikipedia URL. I have to create a shortened URL for the Portuguese page as well, don't know why Telegram keeps complaining about it.

https://github.com/rougeth/i17obot/commit/c7982c4f5e75e294e11bdb6ddaca634a311c3332

**Comment by rougeth** [comment]
Folks, I'm going to close this one. If there is any problem or feature you would like to have on the bot, please open an issue so we can work on it :)

Thank you!
