### ISSUE TITLE
Show active project when using /project command

### ISSUE THREAD

**Issue by rougeth** [rougeth/i17obot#8]
The `/project` command should indicate which project is currently active and the options to be selected should filter out the current one.

An example, if the active project is `Python` and the other available projects are `Jupyter` and `Django`, we should have something like:

![IMG_5473 2](https://user-images.githubusercontent.com/431892/81227014-449d7100-8fdb-11ea-8411-59e292a3171c.JPG)

**Comment by loyannec** [comment]
I'm working on this.
